title: "Research Data Management"
remote_theme: ubc-library-rc/rc-theme
color_scheme: rc
author: Eugene Barsky, Billie Hu, Paul Lesack, Andrew Li
github_repo_url: "https://github.com/ubc-library-rc/rdm/"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_name: "Creative Commons Attribution 4.0 International License"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"
description: "Research Data Management"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - github-pages
  - jekyll-include-cache
